sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libsdl2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Werror -Wno-format-security -Wno-undefined-var-template $CXXFLAGS" ..
  - make
  - make igor
  - make mihail
  - sudo make install

env:
  matrix:
    - CXXFLAGS=
    - CXXFLAGS=-DWIZARD
